In [10]:
import pandas as pd 

df = pd.read_csv('german_credit_data.csv')
df.head()

df.columns

Index(['id', 'Age', 'Sex', 'Job', 'Housing', 'Saving accounts',
       'Checking account', 'Credit amount', 'Duration', 'Purpose', 'Risk'],
      dtype='object')

In [17]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

def createXy(df, input_columns, output_column):
    
    minmax = MinMaxScaler()
    onehot = OneHotEncoder(sparse=False, drop='first') ##verificar parametros pois preguiça agora :P
    
    df.dropna(axis=0, inplace=True) ## axis=1 colunas, axis=0 linhas
    
    X = df[input_columns].copy()
    X_num = X.select_dtypes(exclude='object')
    X_num = minmax.fit_transform(X_num)
    X_num = pd.DataFrame(data=X_num, columns=X.select_dtypes(exclude='object').columns)
    
    columns = []
    X_cat = X.select_dtypes(include='object')
    X_cat = onehot.fit_transform(X_cat)
    for c, values in zip(X.select_dtypes(include='object').columns, onehot.categories_):
        for value in values[1:]:
            columns.append(f'{c}_{value}')
    print(columns)
    X_cat = pd.DataFrame(data=X_cat, columns = columns)
    
    X = X_num.join(X_cat)
    y = df[output_column].copy()
    
    return X, y

X, y = createXy(df, ['Age', 'Sex', 'Job', 'Housing', 'Saving accounts',
       'Checking account', 'Credit amount', 'Duration', 'Purpose'], 'Risk')
X

['Sex_male', 'Housing_own', 'Housing_rent', 'Saving accounts_moderate', 'Saving accounts_quite rich', 'Saving accounts_rich', 'Checking account_moderate', 'Checking account_rich', 'Purpose_car', 'Purpose_domestic appliances', 'Purpose_education', 'Purpose_furniture/equipment', 'Purpose_radio/TV', 'Purpose_repairs', 'Purpose_vacation/others']

,Age,Job,Credit amount,Duration,Sex_male,Housing_own,Housing_rent,Saving accounts_moderate,Saving accounts_quite rich,Saving accounts_rich,Checking account_moderate,Checking account_rich,Purpose_car,Purpose_domestic appliances,Purpose_education,Purpose_furniture/equipment,Purpose_radio/TV,Purpose_repairs,Purpose_vacation/others
0,0.053571,0.666667,0.312707,0.636364,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.464286,0.666667,0.419110,0.545455,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.607143,0.666667,0.253141,0.272727,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.285714,1.000000,0.367644,0.454545,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.160714,1.000000,0.273198,0.363636,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,0.517857,0.333333,0.080835,0.272727,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
518,0.196429,1.000000,0.202942,0.454545,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
519,0.375000,1.000000,0.197322,0.363636,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
520,0.071429,0.666667,0.086456,0.590909,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
521,0.142857,0.666667,0.236941,0.590909,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0